name: 上传到七牛存储
on: push

jobs:
  job1:
    name: "上传到七牛云任务"
    runs-on: Ubuntu-20.04
    steps:
    - name: 检索文件 # checkout
      uses: actions/checkout@v2

    - name: 执行上传
      uses: luochongfei/up2qn@master
      with:
        bucket: 'static'
        access_key: 'TmL4q74drl4FTezf5RhBnXaHFLkwMh98JvTl1ZCz'
        secret_key: 'B_LuBetoZYecVqVhUXwObkYlfA0UvdtoUqEk-Spj'
        local_dir: 'web'
        local_exclude_dir: 'node_modules'
