name: 上传到七牛
on: push

jobs:
  job1:
    name: "up"
    runs-on: ubuntu-latest
    steps:
    - name: Uptoc Action
      uses: saltbo/uptoc@master
      with:
        driver: qiniu
        region: cn-south-1
        bucket: static
        exclude: .cache,test
        dist: public
      env:
        UPTOC_UPLOADER_AK: ${{ secrets.AK }}
        UPTOC_UPLOADER_SK: ${{ secrets.SK }}
